### ISSUE TITLE
User has landed on connect app instead of community app.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#1]
**Steps** :
1. Go to https://qa-community-app.topcoder-dev.com/members/TonyJ
2. Click Login button.
3. Go to sign up section 
4. Fill the data, submit the form and observe the email

**Expected** : 
User should landed on community app while clicking on confirmation email where he has registered  the acc.

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/92589549-6e80e000-f2ba-11ea-8491-7e5785d5a346.png)
![image](https://user-images.githubusercontent.com/25297859/92589640-907a6280-f2ba-11ea-8636-6919ccd09dbb.png)

**Comment by sachin-maheshwari** [comment]
For the time being i hard coded at auth0 "connection" end. 

I need to plan to fix it. Default we can take to topcoder-dev.com / topcoder.com

**Comment by sachin-maheshwari** [comment]
return url will depends on https://www.topcoder.com/user-selection/

**Comment by sachin-maheshwari** [comment]
Implemented same as per https://www.topcoder.com/user-selection/ , that means if user is coming from Connect (regSorce=tcBusiness), should return on Connect else (all remaining cases) it should return on to "https://www.topcoder.com/start" .

**Comment by sachin-maheshwari** [comment]
For testing, this is dedicated env - https://connect-auth0.topcoder-dev.com/

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari : If user signup from Connect app, user is returning to "https://www.topcoder-dev.com/start" instead of Connect url. 
So is it like user will be return to Connect only if signed up from TC link (www.topcoder-dev.com ->I'm a customer) ? Please clarify the doubt.

[connect_redirecturl.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5325299/connect_redirecturl.zip)

<img width="549" alt="connect_activationurl" src="https://user-images.githubusercontent.com/55895538/95041743-8cebc700-0712-11eb-9d86-aa7b55dbe879.png">

For others returnurl is correctly displayed as start

Community app:
[community_redirect_url.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5325303/community_redirect_url.zip)
<img width="670" alt="community_redirecturl" src="https://user-images.githubusercontent.com/55895538/95041794-b7d61b00-0712-11eb-9587-2c151d1303cc.png">

OR app:
[OR_redirectionurl.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5325309/OR_redirectionurl.zip)
<img width="640" alt="OR_redirectionurl" src="https://user-images.githubusercontent.com/55895538/95041839-cde3db80-0712-11eb-9d55-8be400ec9121.png">

Direct app:
[Direct_redirectionurl.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5325315/Direct_redirectionurl.zip)
<img width="575" alt="direct_activationurl" src="https://user-images.githubusercontent.com/55895538/95041866-df2ce800-0712-11eb-82c9-e410c200a82d.png">

**Comment by sandhiyakavi** [comment]
If we signup from Community app challenges page, The return url in activation mail is Community app challenges url instead of start page (https://www.topcoder-dev.com/start )

![image (8)](https://user-images.githubusercontent.com/55895538/96415383-7a50b200-1229-11eb-88af-1209dffaa644.png)

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi @SathyaJayabal  @drasticdpk  Lets collect all "after-activation-url" issues in one master issue ?

**Comment by sandhiyakavi** [comment]
Verified on Staging. The return URL for signup from Community is correctly displaying as Start page.

<img width="1440" alt="Screenshot 2020-10-21 at 4 41 23 PM" src="https://user-images.githubusercontent.com/55895538/96713110-0eae4680-13db-11eb-9a6e-a4872c7ed4cc.png">
