### ISSUE TITLE
Not able to login Arena.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#33]
Description: 

Not able to login Arena. It is loading for a long time. Also getting console error ERR_cert_Date_Invalid

<img width="960" alt="arena_notloggingin" src="https://user-images.githubusercontent.com/55895538/95308630-1fcc6300-08c5-11eb-9fb4-76620bcd7a61.png">

**Comment by sachin-maheshwari** [comment]
That is not related to "new auth". you can verify on prod by this - https://accounts-auth0.topcoder.com/?retUrl=https://arena.topcoder.com

**Comment by mtwomey** [comment]
@sachin-maheshwari Can you confirm that after the cut-over, going to:

`http://arena.topcoder.com/`   will take the user to ->
`https://accounts-auth0.topcoder.com/?retUrl=https://arena.topcoder.com` ?

**Comment by sachin-maheshwari** [comment]
@mtwomey it is going even on dev now, please try this - https://arena.topcoder-dev.com/  This is controlled from docker-supply.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari ,  
1. Opening `https://arena.topcoder-dev.com/`  opens the login screen, but after login , getting redirected to `https://www.topcoder-dev.com/` instead of arena. 
Using `https://accounts-auth0.topcoder.com/?retUrl=https://arena.topcoder.com` directly redirects the user to `https://arena.topcoder-dev.com/` correctly.

2. If we access Arena on dev `https://arena.topcoder-dev.com/` , the page keeps on loading with the message
"Completing login... One moment please...". This could be because arena not available on dev env

[arena.mp4.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5413552/arena.mp4.zip)

Below url in production is working well. User gets logged in and then taken to the arena as expected and arena loads.
https://accounts-auth0.topcoder.com/?retUrl=https://arena.topcoder.com

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal thank you! Lets add QA pass label ?

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , see point 1
Opening https://arena.topcoder-dev.com/ opens the login screen, but after login , getting redirected to https://www.topcoder-dev.com/ instead of arena.

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal fixed. Please verify.

**Comment by SathyaJayabal** [comment]
verified on dev
[arena.mov.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5421535/arena.mov.zip)

**Comment by sandhiyakavi** [comment]
Verified on Prod.

![image](https://user-images.githubusercontent.com/55895538/97858645-cda32400-1d42-11eb-8a05-1b70fbd48b1b.png)

**Comment by 0ne0rZer0** [comment]
Hey, I can't reach arena.topcoder.com/index, first it gets redirected to https://accounts-auth0.topcoder.com/?retUrl=https:%2F%2Farena.topcoder.com%2Findex.html then again to this arena.topcoder.com/index. This loops infinitely. 
Please help.
