### ISSUE TITLE
User data is not displayed after login; If user tries to register an account with already associated social login

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#39]
### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Click Sign Up
3. Select GitHub (User should already be logged in to Github; and the user should have a topcoder account associated with that email)
4. Select the Country and Handle
5. Click Continue
6. Check the profile dropdown and go inside the profile page

### Actual behavior
- User data is not displayed after login; If user tries to register an account with already associated social login

### Expected behavior
- Should display the correct data

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by mtwomey** [comment]
Let's compare to existing behavior to understand if this is related to the new auth or just a general issue?

**Comment by sachin-maheshwari** [comment]
Now we are giving this error in pop-up - "Social Registration Error: Email address 'soorooshchabokroo@gmail.com' has already been registered, please use another one. Please retry."

**Comment by sachin-maheshwari** [comment]
@codejamtc / @sandhiyakavi please share more information if issue is still persisting or close it please.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Tried the above scenario again. This issue is still existing.

Steps to Reproduce:
1. Signup using GitHub account (There should be already Topcoder account created, with same Email address).
2. Observe the logged in Topcoder app.

1. Profile pic not displayed.
![image](https://user-images.githubusercontent.com/55895538/103866295-e7793280-5108-11eb-96b7-4652cb7159da.png)

2. Getting 404 HTTP error for Profile settings page.

![image](https://user-images.githubusercontent.com/55895538/103866386-07a8f180-5109-11eb-9a37-ca922ceecee5.png)

3. Dashboard, Profile and Payments sub menu are not displayed.
![image](https://user-images.githubusercontent.com/55895538/103866476-358e3600-5109-11eb-8f2e-fa3f73d6b51f.png)

Note: This issue is happening for Direct Login as well as GitHub login after signing up with GitHub account.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Member api is down.(https://topcoder.slack.com/archives/C0K5RSB8E/p1610005617043800)

Will check again.Once its up.
